export default [
  {
    index: 'blank',
    label: '1',
    title: '',
    subtitle: '',
  },
  {
    index: 'cover',
    label: '2',
    title: 'ÉTICA DO DISCURSO',
    subtitle: 'Professor Rafael Adolfo',
  },
  {
    index: '3',
    label: '3',
    title: 'Jürgen Habermas',
    subtitle: 'Biografia',
    topics: ['Nasceu em 18 de junho de 1929;', 'Düsseldorf, Alemanha;'],
  },
  {
    index: '4',
    label: '4',
    title: 'Jürgen Habermas',
    subtitle: 'Desenvolvimento profissional',
    topics: [
      '<b>1954</b> Doutorado em filosofia, Universidade de Bonn;',
      '<b>1956</b>-<b>1959</b> Trabalhou como assistente de Theodor Adorno na Universidade de Frankfurt;',
      'A partir de <b>1968</b> trabalhou no Instituto Max Planck e na Nova Escola de Pesquisa Social de Nova York.',
    ],
  },
  {
    index: '5',
    label: '5',
    title: 'Jürgen Habermas',
    subtitle: 'Corrente filosófica',
    topics: [
      'Intensa participação em movimentos sociais;',
      'Emergiu como um dos principais expoentes da segunda geração da <b>Escola de Frankfurt</b>;',
      'Sempre denunciou o que via como <b>“elitismo”</b> do movimento estudantil;',
      'Sua principal influência e corrente filosófica, foi a Escola de Frankfurt.',
    ],
  },
  {
    index: '6',
    label: '6',
    title: 'Jürgen Habermas',
    subtitle: 'Principais obras',
    topics: [
      'Mudança Estrutural da Esfera Pública <b>(1962)</b>;',
      'Conhecimento e Interesse <b>(1968)</b>;',
      'Teoria do Agir Comunicativo <b>(1981)</b>;',
      'O Discurso Filosófico da Modernidade <b>(1985)</b>;',
      'A Ética da Discussão e a Questão da Verdade <b>(2003)</b>;',
      'Direito e Democracia <b>(2003)</b>.',
    ],
  },
  {
    index: '7',
    label: '7',
    title: '',
    subtitle: '',
    backgroundText: 'Principais Ideias',
    topics: ['Teoria da ação comunicativa;', 'Ética do discurso.'],
  },
  {
    index: '7-8',
    label: '7-8',
    title: '',
    subtitle: '',
    backgroundText: '',
    autoplay: true,
    timeout: 1000,
  },
  {
    index: '8',
    label: '8',
    title: 'Teoria da ação comunicativa',
    subtitle: '',
    topics: [
      'Base: <b>Materialismo histórico dialético</b> (Marx), o <b>funcionalismo</b> (Max Weber) e <b>Escola de Frankfurt</b>;',
      'Teoria de interpretação do mundo e da socialização;',
      'A socialização é complexa (processos individuais);',
      'A comunicação é o mais fundamental processo humano;',
      'Fundamentação da ética - Convencimento com base da comunicação;',
      'Processo de comunicação livre e racional - Consolidação da democracia;',
      'A razão surge como uma proposta de emancipação do ser humano.',
    ],
  },
  {
    index: '9',
    label: '9',
    title: 'Ética do discurso',
    subtitle: '',
    topics: [
      'Fundamenta-se na Teoria da Ação Comunicativa;',
      'Conceito de Razão: fenômenos, princípios, agir comunicativo;',
      'Visa garantir a igualdade de condições entre os sujeitos, tanto na comunicação assim como na própria condição de vida;',
      '“Princípio do discurso”: Argumentação racional e não coercitiva;',
      'Argumentos igualmente válidos.',
    ],
  },
  {
    index: '9',
    label: '9',
    title: 'Referências',
    subtitle: '',
    topics: [
      'ARANHA, Maria Lucia de Arruda. <b>FILOSOFANDO</b>: introdução à filosofia. 2. ed. São Paulo: Moderna, 1993. 390 p. Disponível em: http://200.135.161.12/~sergio.sell/m%C3%B3dulo%204/Livro%20Filosofando%20Aranha%20-%20livro%20completo.pdf. Acesso em: 13 mar. 2021.',
      'COTRIM, Gilberto; FERNANDES, Mirna. <b>Fundamentos de Filosofia.</b> 4. ed. São Paulo: Saraiva, 2016. 514 p. Disponível em: http://www.joinville.ifsc.edu.br/~sergio.sell/FUNDAMENTOS_de_FILOSOFIA_Cotrim.pdf. Acesso em: 13 mar. 2021.',
      'ESCOLA de Frankfurt. 2018. Disponível em: https://brasilescola.uol.com.br/sociologia/a-escola-frankfurt.htm. Acesso em: 13 mar. 2021.',
    ],
  },
  {
    index: '10',
    label: '10',
    title: 'Referências',
    subtitle: '',
    topics: [
      'FRAZÃO, Dilva. <b>Jürgen Habermas</b>: filósofo alemão. Filósofo alemão. 2020. Disponível em: https://www.ebiografia.com/jurgen_habermas/. Acesso em: 14 mar. 2021.',
      'HTTPS://GUIADOESTUDANTE.ABRIL.COM.BR/ESPECIAIS/JURGEN-HABERMAS/, Guia do Estudante Leia Mais Em:. <b>JÜRGEN HABERMAS</b>. 2017. Disponível em: https://guiadoestudante.abril.com.br/especiais/jurgen-habermas/. Acesso em: 13 mar. 2021.',
      'JORNAL GRANDE BAHIA (Bahia). <b>Jürgen Habermas, 90 anos de inquietude filosófica</b>. 2019. Disponível em: https://www.jornalgrandebahia.com.br/2019/06/jurgen-habermas-90-anos-de-inquietude-filosofica/. Acesso em: 19 mar. 2021.',
      'JÜRGEN Habermas. 2015. Disponível em: https://brasilescola.uol.com.br/sociologia/jurgen-habermas.htm. Acesso em: 13 mar. 2021.',
    ],
  },
  {
    index: '10',
    label: '10',
    title: 'Referências',
    subtitle: '',
    topics: [
      'MEDEIROS, Alexsandro M.. <b>Ética do Discurso</b>. 2016. Disponível em: https://www.sabedoriapolitica.com.br/products/etica-do-discurso/#:~:text=No%20caso%20de%20Habermas%2C,Sup%C3%B5e%20normas%20racionalmente%20valid%C3%A1veis. Acesso em: 15 mar. 2021.',
      'PONZILACQUA, Marcio Henrique Pereira. <b>Ética do discurso</b>. 2017. Disponível em: https://enciclopediajuridica.pucsp.br/verbete/144/edicao-1/etica-do-discurso. Acesso em: 13 mar. 2021.',
    ],
  },
]
