export default [
  {
    index: 'blank',
    label: '1',
    title: '',
    subtitle: '',
  },
  {
    index: 'cover',
    label: '2',
    title: 'ÉTICA DO DISCURSO',
    subtitle: 'Professor Rafael Adolfo',
  },
  {
    index: '3',
    label: '3',
    title: 'Jürgen Habermas',
    subtitle: 'Biografia',
    topics: ['Nasceu em 18 de junho de 1929;', 'Düsseldorf, Alemanha;'],
  },
  {
    index: '4',
    label: '4',
    title: 'Jürgen Habermas',
    subtitle: 'Desenvolvimento profissional',
    topics: [
      '<b>1954</b> Doutorado em filosofia, Universidade de Bonn;',
      '<b>1956</b>-<b>1959</b> Trabalhou como assistente de Theodor Adorno na Universidade de Frankfurt;',
      'A partir de <b>1968</b> trabalhou no Instituto Max Planck e na Nova Escola de Pesquisa Social de Nova York.',
    ],
  },
  {
    index: '5',
    label: '5',
    title: 'Jürgen Habermas',
    subtitle: 'Corrente filosófica',
    topics: [
      'Intensa participação em movimentos sociais;',
      'Emergiu como um dos principais expoentes da segunda geração da <b>Escola de Frankfurt</b>;',
      'Sempre denunciou o que via como <b>“elitismo”</b> do movimento estudantil;',
      'Sua principal influência e corrente filosófica, foi a Escola de Frankfurt.',
    ],
  },
  {
    index: '6',
    label: '6',
    title: 'Jürgen Habermas',
    subtitle: 'Principais obras',
    topics: [
      'Mudança Estrutural da Esfera Pública <b>(1962)</b>;',
      'Conhecimento e Interesse <b>(1968)</b>;',
      'Teoria do Agir Comunicativo <b>(1981)</b>;',
      'O Discurso Filosófico da Modernidade <b>(1985)</b>;',
      'A Ética da Discussão e a Questão da Verdade <b>(2003)</b>;',
      'Direito e Democracia <b>(2003)</b>.',
    ],
  },
  {
    index: '7',
    label: '7',
    title: '',
    subtitle: '',
    backgroundText: 'Principais Ideias',
    topics: ['Teoria da ação comunicativa;', 'Ética do discurso.'],
  },
  {
    index: '8',
    label: '8',
    title: 'Teoria da ação comunicativa',
    subtitle: '',
    topics: [
      'Base: <b>Materialismo histórico dialético</b> (Marx), o <b>funcionalismo</b> (Max Weber) e <b>Escola de Frankfurt</b>;',
      'Teoria de interpretação do mundo e da socialização;',
      'A socialização é complexa (processos individuais);',
      'A comunicação é o mais fundamental processo humano;',
      'Fundamentação da ética - Convencimento com base da comunicação;',
      'Processo de comunicação livre e racional - Consolidação da democracia;',
      'A razão surge como uma proposta de emancipação do ser humano.',
    ],
  },
  {
    index: '9',
    label: '9',
    title: 'Ética do discurso',
    subtitle: '',
    topics: [
      'Mudança Estrutural da Esfera Pública <b>(1962)</b>;',
      'Conhecimento e Interesse <b>(1968)</b>;',
      'Teoria do Agir Comunicativo <b>(1981)</b>;',
      'O Discurso Filosófico da Modernidade <b>(1985)</b>;',
      'A Ética da Discussão e a Questão da Verdade <b>(2003)</b>;',
      'Direito e Democracia <b>(2003)</b>;',
    ],
  },
]
